AllCops:
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

# Disable documentation checking until a class needs to be documented once
Documentation:
  Enabled: false

# Don't require magic comment at the top of every file
Encoding:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
